apiVersion: v1
kind: Pod
metadata:
   name: roto-app-pod
   labels:
        name: roto-app-pod
        app: demo-roto-app
spec:
    containers:
    - name: roto-app
      image: terencebor/rotator:lb
      ports:
      - containerPort: 8080
